In [ ]:
import numpy as np

In [ ]:
data=np.array([[3.87,2.65,0],
              [2.65,3.63,0],
              [4.93,5.50,0],
              [2.83,2.95,0],
              [4.07,4.00,0],
              [8.27,3.57,1],
              [6.36,3.09,1],
              [7.99,2.97,1],
              [9.76,1.42,1],
              [8.76,4.6,1]])

In [ ]:
data[:,1]

array([2.65, 3.63, 5.5 , 2.95, 4.  , 3.57, 3.09, 2.97, 1.42, 4.6 ])

In [ ]:
import pandas as pd

In [ ]:
# df=pd.DataFrame(data=data,columns={"x1":data[:,0],"x2":data[:,1],"y":data[:,2]})
df=pd.DataFrame(data=data,columns=["x1","x2","y"])

In [ ]:
df

x1    x2    y
0  3.87  2.65  0.0
1  2.65  3.63  0.0
2  4.93  5.50  0.0
3  2.83  2.95  0.0
4  4.07  4.00  0.0
5  8.27  3.57  1.0
6  6.36  3.09  1.0
7  7.99  2.97  1.0
8  9.76  1.42  1.0
9  8.76  4.60  1.0

In [ ]:
x=df[['x1','x2']]

In [ ]:
x

x1    x2
0  3.87  2.65
1  2.65  3.63
2  4.93  5.50
3  2.83  2.95
4  4.07  4.00
5  8.27  3.57
6  6.36  3.09
7  7.99  2.97
8  9.76  1.42
9  8.76  4.60

In [ ]:
y=df[['y']]

In [ ]:
y

y
0  0.0
1  0.0
2  0.0
3  0.0
4  0.0
5  1.0
6  1.0
7  1.0
8  1.0
9  1.0

In [ ]:
df['y']=df['y'].astype(int)

In [ ]:
df

x1    x2  y
0  3.87  2.65  0
1  2.65  3.63  0
2  4.93  5.50  0
3  2.83  2.95  0
4  4.07  4.00  0
5  8.27  3.57  1
6  6.36  3.09  1
7  7.99  2.97  1
8  9.76  1.42  1
9  8.76  4.60  1

In [ ]:
coef=[0.55,0.45,1.25]

In [ ]:
def predict(data_row,coef):
  yhat=coef[0] + coef[1] * data_row[0] + coef[2] * data_row[1]
  return 1/(1+math.exp(-yhat))

  #function ne dynamic banavanu  chhe aa static chhe

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0)

In [ ]:
model1=LinearRegression(fit_intercept=True)

In [ ]:
model1.fit(xtrain,ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
model1.coef_

array([[ 0.19778935, -0.05852555]])

In [ ]:
for data_row in data:
  z= predict(data_row,coef)
  print("expected", data_row[2],"calculated",z,"rountded",round(z))

expected 0.0 calculated 0.03619551521603463 rountded 0
expected 0.0 calculated 1.8099674901558454e-06 rountded 0
expected 0.0 calculated 3.344598830206283e-07 rountded 0
expected 0.0 calculated 0.0001470982771366144 rountded 0
expected 0.0 calculated 4.902292808135479e-05 rountded 0
expected 1.0 calculated 0.9997199726862912 rountded 1
expected 1.0 calculated 0.9745719358906123 rountded 1
expected 1.0 calculated 0.999970032362334 rountded 1
expected 1.0 calculated 0.9999999999918967 rountded 1
expected 1.0 calculated 0.9876119653699826 rountded 1


In [ ]:
import math 

In [ ]:
for i in range(300):
  sum_error=0
  lr=0.001
  for data_row in data:
    z=predict(data_row,coef)
    error=data_row[2]-z
    sum_error += error**2
    coef[0]=coef[0]+lr*error*z*(1-z)
    coef[1]=coef[1]+lr*error*data_row[0]*z*(1-z)
    coef[2]=coef[2]+lr*error*data_row[1]*z*(1-z)
  print(sum_error)

  #number of iterartion is aslocalled epock

0.0021108822769477517
0.0021108804247774553
0.002110878572610902
0.0021108767204481085
0.0021108748682890895
0.0021108730161338274
0.0021108711639823345
0.002110869311834617
0.0021108674596906464
0.002110865607550439
0.002110863755414029
0.0021108619032813455
0.0021108600511524555
0.0021108581990273083
0.002110856346905927
0.0021108544947883155
0.002110852642674463
0.0021108507905643753
0.0021108489384580563
0.0021108470863555
0.0021108452342567083
0.0021108433821616507
0.0021108415300703947
0.002110839677982895
0.0021108378258991286
0.002110835973819148
0.0021108341217429176
0.002110832269670466
0.0021108304176017502
0.002110828565536831
0.0021108267134756437
0.0021108248614182304
0.00211082300936457
0.002110821157314674
0.002110819305268532
0.0021108174532261594
0.0021108156011875596
0.0021108137491527026
0.0021108118971216064
0.002110810045094267
0.002110808193070695
0.00211080634105087
0.0021108044890348105
0.002110802637022521
0.0021108007850139682
0.002110798933009203
0.002110797

In [ ]:
from sklearn.datasets import load_breast_cancer
df1=pd.DataFrame()
df1=load_breast_cancer()
type(df1)

sklearn.utils.Bunch

In [ ]:
df1.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [ ]:
df1['data']
df1['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,